#!/usr/bin/env zsh

## Environment variables
export COLORTERM="truecolor"

# ZSH Config
export ZSH_COMPDUMP="$XDG_CACHE_HOME/zsh/.zcompdump-${HOST/.*/}-${ZSH_VERSION}"
export ZSH="$HOME/.oh-my-zsh"
export ZSH_THEME="avit"
export ENABLE_CORRECTION="false"
export DISABLE_MAGIC_FUNCTIONS="true"
export COMPLETION_WAITING_DOTS="false"
export DISABLE_UNTRACKED_FILES_DIRTY="true"
export HISTSIZE=10000
export SAVEHIST=10000
export HISTFILE="$HOME/.zsh_history"
export HIST_STAMPS="yyyy-mm-dd"

# Misc
export COMPOSER_HOME="$XDG_CONFIG_HOME/composer"
export ASDF_NPM_DEFAULT_PACKAGES_FILE="$XDG_CONFIG_HOME/asdf/.default-npm-packages"
export ASDF_PYTHON_DEFAULT_PACKAGES_FILE="$XDG_CONFIG_HOME/asdf/.default-python-packages"
export PNPM_HOME="$XDG_DATA_HOME/pnpm"
export BUN_INSTALL="$HOME/.bun"
export PYENV_ROOT="$HOME/.pyenv"

# Path
export PATH="$HOME/bin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$COMPOSER_HOME/vendor/bin:$PATH"
export PATH="$PNPM_HOME:$PATH"
export PATH="$BUN_INSTALL/bin:$PATH"
export PATH="$HOME/.phpenv/bin:$PATH"
export PATH="$HOME/neovim/bin:$PATH"
export PATH="$PNPM_HOME:$PATH"
export PATH="$HOME/.deno/bin:$PATH"
export PATH="$PYENV_ROOT/bin:$PATH"

# Export DISPLAY on WSL
if grep -qi microsoft /proc/version; then
    export DISPLAY="$(/sbin/ip route | awk '/default/ { print $3 }'):0"
    export LIBGL_ALWAYS_INDIRECT=1
fi

# ZSH Config
plugins=(
  asdf
  git
  fzf
  vi-mode
  direnv
)

source "$ZSH"/oh-my-zsh.sh

# FZF
source /usr/share/doc/fzf/examples/key-bindings.zsh
source /usr/share/doc/fzf/examples/completion.zsh

source "$ZDOTDIR"/dircolors # Generated by: $ dircolors $ZDOTDIR/.dircolors > $ZDOTDIR/dircolors
source "$ZDOTDIR"/aliases
source "$ZDOTDIR"/functions

# Share history between shells
setopt SHARE_HISTORY

bindkey -s ^f "tmux-sessionizer\n"
bindkey -v
bindkey -s ^a "tmux\n"
bindkey -M vicmd ^e edit-command-line

# Remove mode switching delay.
KEYTIMEOUT=5

# Change cursor shape for different vi modes.
function zle-keymap-select {
    if [[ ${KEYMAP} == vicmd ]] || [[ $1 = 'block' ]]; then
        echo -ne '\e[1 q'

    elif [[ ${KEYMAP} == main ]] ||
        [[ ${KEYMAP} == viins ]] ||
        [[ ${KEYMAP} = '' ]] ||
        [[ $1 = 'beam' ]]; then
        echo -ne '\e[5 q'
    fi
}
zle -N zle-keymap-select

# Use beam shape cursor on startup.
echo -ne '\e[5 q'

# Use beam shape cursor for each new prompt.
precmd() {
    echo -ne '\e[5 q'
}
precmd_functions+=(_fix_cursor)

# Completion
_comp_options+=(globdots) # complete dotfiles

# WP CLI
[ -s "$HOME/.local/completions/wp-completions.bash" ] && source "$HOME"/.local/completions/wp-completion.bash

# Bun
[ -s "/home/hendrik/.bun/_bun" ] && source "$HOME/.bun/_bun"

# PHPenv
if command -v phpenv &> /dev/null; then eval "$(phpenv init -)"; fi

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && 
eval "$(pyenv init -)" 

# Overrides
[ -s "$ZDOTDIR/.zshrc.local" ] && source "$ZDOTDIR/.zshrc.local"

. $HOME/.nix-profile/etc/profile.d/hm-session-vars.sh
