# ZSH Config

plugins=(
  git
  z
)

source $ZSH/oh-my-zsh.sh

# TODO:Find better way for this
source $HOME/.local/share/nvim/plugged/gruvbox/gruvbox_256palette.sh

source $ZDOTDIR/dircolors # Generated by: $ dircolors $ZDOTDIR/.dircolors > $ZDOTDIR/dircolors
source $ZDOTDIR/aliases
source $ZDOTDIR/functions

# Completion
_comp_options+=(globdots) # complete dotfiles


# WP CLI
source $HOME/.local/completions/wp-completion.bash

# PHPenv
eval "$(phpenv init -)"

# NVM
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

