#!/usr/bin/env bash

alias e="explorer.exe"
alias vim="nvim"
alias v="nvim"
# alias nvim-lazy="NVIM_APPNAME=nvim-lazy nvim"
# alias vl="nvim-lazy"
alias vf="fzf | xargs nvim"
alias dc="docker-compose"
alias gcf="git commit --fixup"
alias gwt="git worktree"
alias gwtf="git-fetch-worktree"
alias gwtl="git worktree list"
alias gwtr="git worktree remove"
alias gwtm="git worktree remove"
alias gwta="git-add-worktree"
alias grbid="git-rebase-interactive-branch-root"
alias ssl='openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout ssl.key -out ssl.cert -subj "/CN=127.0.0.1/"'
alias dot='git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias gpriv="git config user.email 'hendrikbursian@protonmail.com' && git config user.name 'Hendrik Bursian'"
alias gu="git undo"
alias ssl='openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout ssl.key -out ssl.cert -subj "/CN=127.0.0.1/"'
alias x="chmod +x"
alias f="fzf --preview 'cat {}'"
alias y="yarn"
alias gcl="gitlab-ci-local"
alias pd="popd"
alias pud="pushd"
alias t="trans"

alias go-reshim='asdf reshim golang && export GOROOT="$(asdf where golang)/go/"'

# This is specific to WSL 2. If the WSL 2 VM goes rogue and decides not to free
# up memory, this command will free your memory after about 20-30 seconds.
#   Details: https://github.com/microsoft/WSL/issues/4166#issuecomment-628493643
alias drop_cache="sudo sh -c \"echo 3 >'/proc/sys/vm/drop_caches' && swapoff -a && swapon -a && printf '\n%s\n' 'Ram-cache and Swap Cleared'\""
