#!/usr/bin/env zsh

function update_nvim {
  git clone git@github.com:neovim/neovim.git $HOME/neovim
  
  cd $HOME/neovim
  rm -r build/
  make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$HOME/neovim"
  make install

  export PATH="$HOME/neovim/bin:$PATH"
}
