# ZSH Config

plugins=(
  git
  z
)

source $ZSH/oh-my-zsh.sh

# TODO:Find better way for this
[ -s "$HOME/.local/share/nvim/plugged/gruvbox/gruvbox_256palette.sh" ] && source $HOME/.local/share/nvim/plugged/gruvbox/gruvbox_256palette.sh

source $ZDOTDIR/dircolors # Generated by: $ dircolors $ZDOTDIR/.dircolors > $ZDOTDIR/dircolors
source $ZDOTDIR/aliases
source $ZDOTDIR/functions

# Completion
_comp_options+=(globdots) # complete dotfiles

if command -v phpenv &> /dev/null
then
  # PHPenv
  eval "$(phpenv init -)"
fi

# WP CLI
[ -s "$HOME/.local/completions/wp-completions.bash" ] && source $HOME/.local/completions/wp-completion.bash

export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"  # Added by n-install (see http://git.io/n-install-repo).

[ -s "$ZDOTDIR/.zshrc.local" ] && source "$ZDOTDIR/.zshrc.local"
