#!/usr/bin/env bash

alias e="explorer.exe"
alias c="code"
alias v="vim"
alias gcf="git commit --fixup"
alias ssl='openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout ssl.key -out ssl.cert -subj "/CN=127.0.0.1/"'
alias dot="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
alias vim="nvim"
alias gpriv="git config user.email 'hendrikbursian@pm.me' && git config user.name 'Hendrik Bursian'"
