#!/usr/bin/env bash

alias e="explorer.exe"
alias c="code-insiders"
alias vim="nvim"
alias v="vim"
alias vf="fzf | xargs nvim"
alias dc="docker-compose"
alias gcf="git commit --fixup"
alias gwt="git worktree"
alias gwtf="git-make-worktree"
alias gwtl="git worktree list"
alias gwtr="git worktree remove"
alias gwta="git-add-worktree"
# rebase interactive towards default branch from root of branch
alias grbid="git rebase --interactive $(git log $(git remote show origin | sed -n '/HEAD branch/s/.*: //p')..$(git branch --show-current) --oneline | tail -1 | awk '{ print $1 }')~1"
alias ssl='openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout ssl.key -out ssl.cert -subj "/CN=127.0.0.1/"'
alias dot="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
alias gpriv="git config user.email 'hendrikbursian@pm.me' && git config user.name 'Hendrik Bursian'"
alias gu="git undo"
alias ssl='openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout ssl.key -out ssl.cert -subj "/CN=127.0.0.1/"'
alias x="chmod +x"
alias f="fzf --preview 'cat {}'"
alias y="yarn"
alias copy="xclip -sel clip"

alias go-reshim='asdf reshim golang && export GOROOT="$(asdf where golang)/go/"'
