#!/usr/bin/env zsh

function update_neovim() {
    tmp_path=/tmp/nvim.appimage

    echo "Downloading Neovim Appimage..."
    curl -Lo $tmp_path https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    chmod u+x $tmp_path
    sudo mv $tmp_path /usr/local/bin/nvim

    echo "Neovim updated!"
}
