- name: Install tools
  hosts: 127.0.0.1
  connection: local
  vars:
    packages:
      - apt-transport-https
      - bash
      - brave-browser
      - build-essential
      - curl
      - dash
      - fd-find
      - fzf
      - gcc
      - git
      - gpg
      - htop
      - inotify-tools
      - iputils-ping
      - jq
      - llvm
      - lynx
      - make
      - net-tools
      - ripgrep
      - rsync
      - socat
      - stow
      - tldr
      - tmux
      - tree
      - unzip
      - vim
      - wget
      - yarn
      - zlib1g-dev
      - zsh
  pre_tasks:
    - name: Add brave-browser apt repository
      shell: |
        curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list
      become: true
    - name: Add yarn apt repository
      shell: |
        sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
        echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      become: true
    - name: Upgrade dist
      apt:
        update_cache: true
        upgrade: "dist"
      become: true
      ignore_errors: true
    - name: Update cache
      apt:
        update_cache: true
      become: true
      ignore_errors: true
  tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
        state: latest
      loop: "{{ packages }}"
      become: true
    - name: Add node package managers
      shell: |
        # Install pnpm
        command: curl -fsSL https://get.pnpm.io/install.sh | sh -

        # Install bun
        command: curl -fsSL https://bun.sh/install | bash
