[General]
__userfile__=true

[SavedConfigs]
SavedSettings\1\date=2019-06-06T12:44:33
SavedSettings\1\name=Do. Juni 6 12:44:33 2019
SavedSettings\1\settings\1\connected=false
SavedSettings\1\settings\1\hash=
SavedSettings\1\settings\1\name=DisplayPort-1-3
SavedSettings\1\settings\2\connected=false
SavedSettings\1\settings\2\hash=
SavedSettings\1\settings\2\name=DVI-1-0
SavedSettings\1\settings\3\connected=true
SavedSettings\1\settings\3\currentMode=109
SavedSettings\1\settings\3\currentModeHeight=1200
SavedSettings\1\settings\3\currentModeRate=@Variant(\0\0\0\x87\x42o\xcc\xfa)
SavedSettings\1\settings\3\currentModeWidth=1920
SavedSettings\1\settings\3\enabled=true
SavedSettings\1\settings\3\hash=583dc2a2deeff72f476a167117f672fe
SavedSettings\1\settings\3\name=HDMI-1
SavedSettings\1\settings\3\primary=true
SavedSettings\1\settings\3\rotation=1
SavedSettings\1\settings\3\xPos=0
SavedSettings\1\settings\3\yPos=37
SavedSettings\1\settings\4\connected=true
SavedSettings\1\settings\4\currentMode=109
SavedSettings\1\settings\4\currentModeHeight=1200
SavedSettings\1\settings\4\currentModeRate=@Variant(\0\0\0\x87\x42o\xcc\xfa)
SavedSettings\1\settings\4\currentModeWidth=1920
SavedSettings\1\settings\4\enabled=true
SavedSettings\1\settings\4\hash=a521bad6f3652c29fc14f63647fbf51f
SavedSettings\1\settings\4\name=DP-1
SavedSettings\1\settings\4\primary=false
SavedSettings\1\settings\4\rotation=1
SavedSettings\1\settings\4\xPos=1969
SavedSettings\1\settings\4\yPos=12
SavedSettings\1\settings\5\connected=false
SavedSettings\1\settings\5\hash=
SavedSettings\1\settings\5\name=HDMI-2
SavedSettings\1\settings\6\connected=true
SavedSettings\1\settings\6\currentMode=110
SavedSettings\1\settings\6\currentModeHeight=1080
SavedSettings\1\settings\6\currentModeRate=@Variant(\0\0\0\x87\x42p\0\0)
SavedSettings\1\settings\6\currentModeWidth=1920
SavedSettings\1\settings\6\enabled=true
SavedSettings\1\settings\6\hash=d55e019a6005ab7c2acd710eb1ef0ea6
SavedSettings\1\settings\6\name=DP-2
SavedSettings\1\settings\6\primary=false
SavedSettings\1\settings\6\rotation=1
SavedSettings\1\settings\6\xPos=3888
SavedSettings\1\settings\6\yPos=0
SavedSettings\1\settings\7\connected=false
SavedSettings\1\settings\7\hash=
SavedSettings\1\settings\7\name=HDMI-3
SavedSettings\1\settings\8\connected=false
SavedSettings\1\settings\8\hash=
SavedSettings\1\settings\8\name=DP-3
SavedSettings\1\settings\size=8
SavedSettings\size=1

[currentConfig]
settings\1\connected=false
settings\1\hash=
settings\1\name=DisplayPort-1-3
settings\2\connected=false
settings\2\hash=
settings\2\name=DVI-1-0
settings\3\connected=true
settings\3\currentMode=109
settings\3\currentModeHeight=1200
settings\3\currentModeRate=@Variant(\0\0\0\x87\x42o\xcc\xfa)
settings\3\currentModeWidth=1920
settings\3\enabled=true
settings\3\hash=583dc2a2deeff72f476a167117f672fe
settings\3\name=HDMI-1
settings\3\primary=true
settings\3\rotation=1
settings\3\xPos=0
settings\3\yPos=37
settings\4\connected=true
settings\4\currentMode=109
settings\4\currentModeHeight=1200
settings\4\currentModeRate=@Variant(\0\0\0\x87\x42o\xcc\xfa)
settings\4\currentModeWidth=1920
settings\4\enabled=true
settings\4\hash=a521bad6f3652c29fc14f63647fbf51f
settings\4\name=DP-1
settings\4\primary=false
settings\4\rotation=1
settings\4\xPos=1969
settings\4\yPos=12
settings\5\connected=false
settings\5\hash=
settings\5\name=HDMI-2
settings\6\connected=true
settings\6\currentMode=110
settings\6\currentModeHeight=1080
settings\6\currentModeRate=@Variant(\0\0\0\x87\x42p\0\0)
settings\6\currentModeWidth=1920
settings\6\enabled=true
settings\6\hash=d55e019a6005ab7c2acd710eb1ef0ea6
settings\6\name=DP-2
settings\6\primary=false
settings\6\rotation=1
settings\6\xPos=3888
settings\6\yPos=0
settings\7\connected=false
settings\7\hash=
settings\7\name=HDMI-3
settings\8\connected=false
settings\8\hash=
settings\8\name=DP-3
settings\size=8
