[General]
__userfile__=true
enableBatteryWatcher=true
enableExtMonLidClosedActions=false
enableIdlenessWatcher=true
enableLidWatcher=true
idlenessAction=4
idlenessTimeSecs=900
lidClosedAcAction=4
lidClosedAction=1
lidClosedExtMonAcAction=-1
lidClosedExtMonAction=-1
powerLowAction=-1
powerLowLevel=5
powerLowWarning=30
runCheckLevel=1
showIcon=true
useThemeIcons=true
