[General]
__userfile__=true
iconTheme=
panels=panel1

[desktopswitch]
alignment=Left
labelType=0
rows=1
type=desktopswitch

[mainmenu]
alignment=Left
filterClear=true
type=mainmenu

[panel1]
alignment=-1
animation-duration=0
background-color=@Variant(\0\0\0\x43\x1\xff\xff..44@@\0\0)
background-image=
desktop=1
font-color=@Variant(\0\0\0\x43\x1\xff\xff\xd8\xd8\xde\xde\xe9\xe9\0\0)
hidable=false
iconSize=22
lineCount=1
lockPanel=false
opacity=100
panelSize=28
plugins=mainmenu, desktopswitch, showdesktop, taskbar, volume, tray
position=Bottom
reserve-space=true
show-delay=0
visible-margin=true
width=100
width-percent=true

[showdesktop]
alignment=Right
type=showdesktop

[taskbar]
alignment=Left
autoRotate=true
buttonHeight=100
buttonStyle=IconText
buttonWidth=200
closeOnMiddleClick=true
cycleOnWheelScroll=false
groupingEnabled=false
iconByClass=true
raiseOnCurrentDesktop=false
showDesktopNum=0
showGroupOnHover=true
showOnlyCurrentScreenTasks=false
showOnlyMinimizedTasks=false
showOnlyOneDesktopTasks=true
type=taskbar

[tray]
alignment=Right
type=tray

[volume]
alignment=Right
allwaysShowNotifications=false
device=0
ignoreMaxVolume=false
type=volume
