[General]
__userfile__=true
iconTheme=
panels=panel1

[desktopswitch]
alignment=Left
labelType=0
rows=1
type=desktopswitch

[mainmenu]
alignment=Left
filterClear=true
type=mainmenu

[panel1]
alignment=-1
animation-duration=350
background-color=@Variant(\0\0\0\x43\x1\xff\xff\x33\x33\x33\x33\x33\x33\0\0)
background-image=
desktop=0
font-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
hidable=false
iconSize=22
lineCount=1
lockPanel=false
opacity=46
panelSize=32
plugins=mainmenu, desktopswitch, quicklaunch, showdesktop, taskbar, volume, tray, statusnotifier
position=Bottom
reserve-space=true
show-delay=200
visible-margin=false
width=100
width-percent=true

[quicklaunch]
alignment=Left
apps\1\desktop=/usr/share/applications/pcmanfm-qt.desktop
apps\size=1
type=quicklaunch

[showdesktop]
alignment=Right
type=showdesktop

[statusnotifier]
alignment=Right
type=statusnotifier

[taskbar]
alignment=Left
buttonWidth=200
type=taskbar

[tray]
alignment=Right
type=tray

[volume]
alignment=Right
allwaysShowNotifications=false
device=0
ignoreMaxVolume=false
type=volume
