[General]
__userfile__=true
window_manager=openbox

[Environment]
BROWSER=/snap/bin/brave
GTK_CSD=0
GTK_OVERLAY_SCROLLING=0
TERM=qterminal

[Keyboard]
beep=false
delay=200
interval=10
layout=de
model=pc105
numlock=false
variant=

[Mouse]
accel_factor=60
accel_threshold=0
cursor_theme=breeze_cursors
left_handed=false
