[General]
__userfile__=true
window_manager=openbox

[Environment]
BROWSER=/snap/bin/brave
GTK_CSD=0
GTK_OVERLAY_SCROLLING=0
TERM=qterminal

[Keyboard]
beep=false
delay=203
interval=24
layout=de
model=pc105
numlock=false
variant=

[Mouse]
cursor_theme=breeze_cursors
