- name: Install tools
  hosts: 127.0.0.1
  connection: local
  vars:
    packages:
  tasks:
    - name: Upgrade dist
      apt:
        update_cache: true
        upgrade: "dist"
      become: true
      ignore_errors: true

    - name: Add regolith key
      shell: |
        curl -fsSL https://regolith-desktop.org/regolith.key | gpg --dearmor | sudo tee /usr/share/keyrings/regolith-archive-keyring.gpg > /dev/null
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg] https://regolith-desktop.org/release-3_0-ubuntu-$(. /etc/os-release && echo "$VERSION_CODENAME")-amd64 $(. /etc/os-release && echo "$VERSION_CODENAME") main" | sudo tee /etc/apt/sources.list.d/regolith.list
      become: true

    - name: Install packages
      apt:
        pkg:
          - i3xrocks-battery
          - i3xrocks-cpu-usage
          - i3xrocks-disk-capacity
          - i3xrocks-memory
          - i3xrocks-microphone
          - i3xrocks-net-traffic
          - i3xrocks-updates
          - i3xrocks-volume
          - i3xrocks-wifi
          - regolith-desktop
          - regolith-look-nord
          - regolith-session-flashback
        state: latest
        update_cache: true
      become: true
      ignore_errors: true

    - name: Add Oh my zsh
      shell: |
        chsh -s $(which zsh)
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      ignore_errors: true

    - name: Add node package managers
      shell: |
        # Install bun
        command: curl -fsSL https://bun.sh/install | bash

    - name: Install rust
      shell: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        rm $HOME/.zshenv 2&> /dev/null

    - name: Set docker user group
      shell: |
        sudo usermod -aG docker $USER
