- name: Install asdf
  hosts: 127.0.0.1
  become: no
  vars:
    asdf_user: "{{ lookup('env', 'USER') }}"
    asdf_version: v0.13.1
    asdf_init_shell: false

  roles:
    - role: markosamuli.asdf
      asdf_plugins:
        - name: nodejs
          versions:
            - latest:18
            - latest
          global: latest
        - name: golang
          versions:
            - latest
          global: latest
      environment:
        ASDF_DOWNLOAD_PATH: "$HOME/.asdf"
        ASDF_NPM_DEFAULT_PACKAGES_FILE: "$HOME/.config/asdf/.default-npm-packages"
