- name: Install Dotfiles
  hosts: 127.0.0.1
  tasks:
    - name: Stow dotfiles
      command: "{{ lookup('env', 'HOME') }}/.dotfiles/ubuntu"
    - name: Change Shell
      command: "chsh {{ lookup('env', 'USER') }} --shell /usr/bin/zsh"
      become: true

