- name: Install Neovim
  hosts: 127.0.0.1
  become: true
  vars:
    tmp_path: /tmp/nvim.appimage
    dest_path: /usr/local/bin/nvim

  tasks:
     - name: Download Neovim
       get_url:
         url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
         dest: /tmp/nvim.appimage
     - name: Copy neovim executable
       copy:
         src: /tmp/nvim.appimage
         owner: root
         group: root
         mode: 0755
         dest: /usr/local/bin/nvim
     - name: Remove downloaded file
       file:
         path: /tmp/nvim.appimage
         state: absent
     - name: Installing Neovim plugins
       command: '/usr/local/bin/nvim -E -s -c "source $HOME/.config/nvim/init.vim" -c PlugInstall -c qa'
       ignore_errors: yes
       become: no
     - name: Installing Neovim LSPs
       command: /usr/local/bin/nvim -E -c "source $HOME/.config/nvim/init.vim" -c "LSPInstall eslint sumneko_lua bashls dockerls gopls jedi_language_server tailwindcss html vimls yamlls ansiblels graphql cssls lemminx eslint prismals spectral sqlls taplo tsserver volar zk rome intelephense" -c qa
       become: no
     - name: Cloning telescope-dap
       become: no
       git:
         repo: https://github.com/hendrikbursian/telescope-dap.nvim
         dest: $HOME/workspace/personal/telescope-dap.nvim
         bare: yes
     - name: Checkout master branch
       command: git --git-dir $HOME/workspace/personal/telescope-dap.nvim worktree add $HOME/workspace/personal/telescope-dap.nvim/master master
       ignore_errors: yes
       become: no

     - name: Installing Neovim treesitter grammars
       command: /usr/local/bin/nvim -E -c "source $HOME/.config/nvim/init.vim" -c "TSInstallSync all" -c qa
       ignore_errors: yes
       become: no
