- name: Install Neovim
  hosts: 127.0.0.1
  become: true
  vars:
    tmp_path: /tmp/nvim.appimage
    dest_path: /usr/local/bin/nvim

  tasks:
     - name: Download Neovim
       get_url:
         url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
         dest: /tmp/nvim.appimage
     - name: Copy neovim executable
       copy:
         src: /tmp/nvim.appimage
         owner: root
         group: root
         mode: 0755
         dest: /usr/local/bin/nvim
     - name: Remove downloaded file
       file:
         path: /tmp/nvim.appimage
         state: absent
     - name: Installing Neovim plugins
       shell: /usr/local/bin/nvim -E -s -c PlugInstall -c qa!
       args:
         executable: /usr/bin/zsh
       ignore_errors: yes
       become: no
     - name: Cloning telescope-dap
       become: no
       git:
         repo: https://github.com/hendrikbursian/telescope-dap.nvim
         dest: $HOME/workspace/personal/telescope-dap.nvim
         bare: yes
     - name: Checkout master branch
       command: git --git-dir $HOME/workspace/personal/telescope-dap.nvim worktree add $HOME/workspace/personal/telescope-dap.nvim/master master
       ignore_errors: yes
       become: no

     - name: Installing Neovim treesitter grammars
       shell: /usr/local/bin/nvim -E -s -c "TSInstallSync all" -c qa!
       args:
         executable: /usr/bin/zsh
       ignore_errors: yes
       become: no
