- name: Install Neovim
  hosts: 127.0.0.1

  tasks:
     - name: Download oh my zsh
       get_url:
         url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
         dest: /tmp/install.sh
         mode: 0755
     - name: Remove .oh-my-zsh directory
       file:
         path: $HOME/.oh-my-zsh
         state: absent
     - name: Install oh my zsh
       command: /tmp/install.sh
       environment:
         RUNZSH: no
         KEEP_ZSHRC: yes
     - name: Remove installer
       file:
         path: /tmp/install.sh
         state: absent
     - name: Remove .zshrc.pre-oh-my-zsh
       file:
         path: $HOME/.zshrc.pre-oh-my-zsh
         state: absent
     - name: Remove .zshrc
       file:
         path: $HOME/.zshrc
         state: absent

