- name: Install SSH key
  hosts: 127.0.0.1
  vars:
    source_key: ssh/id_ed25519
    dest_key: $HOME/.ssh/id_ed25519

  tasks:
  - name: Ensure .ssh directory exists.
    file:
      dest: "{{ dest_key | dirname }}"
      mode: 0700
      owner: "{{ lookup('env', 'USER') }}"
      state: directory
  - name: Install ssh key
    copy:
      src: "{{ source_key }}"
      dest: "{{ dest_key }}"
      mode: 0600
      owner: "{{ lookup('env', 'USER') }}"

  - name: Copy public key
    copy:
      src: "{{ source_key }}.pub"
      dest: "{{ dest_key }}.pub"
      mode: 0644
      owner: "{{ lookup('env', 'USER') }}"
