---
- name: Install tools
  hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    packages:
      - apt-transport-https
      - bash
      - build-essential
      - curl
      - dash
      - fd-find
      - fzf
      - gcc
      - git
      - gpg
      - jq
      - llvm
      - lynx
      - make
      - net-tools
      - ripgrep
      - rsync
      - stow
      - tmux
      - tree
      - unzip
      - vim
      - wget
      - zlib1g-dev
      - zsh

    packagesWithDependencies:
      - brave-browser-nightly

  pre_tasks:
  - name: Update apt cache
    apt:
      update_cache: true
      upgrade: "dist"
  - name: Update apt cache
    apt:
      update_cache: true

  tasks:
  - name: Install packages
    apt:
      name: "{{ item }}"
      state: latest
    loop: "{{ packages }}"
  - name: Add brave browser sources
    become: true
    shell: |
      curl -fsSLo /usr/share/keyrings/brave-browser-nightly-archive-keyring.gpg https://brave-browser-apt-nightly.s3.brave.com/brave-browser-nightly-archive-keyring.gpg
      echo "deb [signed-by=/usr/share/keyrings/brave-browser-nightly-archive-keyring.gpg arch=amd64] https://brave-browser-apt-nightly.s3.brave.com/ stable main"| tee /etc/apt/sources.list.d/brave-browser-nightly.list
    become: true
  - name: Update apt cache
    apt:
      update_cache: true
  - name: Install packages with dependencies
    apt:
      name: "{{ item }}"
      state: latest
    loop: "{{ packagesWithDependencies }}"

