---
- name: Install tools
  hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    packages:
      - apt-transport-https
      - bash
      - build-essential
      - curl
      - dash
      - fd-find
      - fzf
      - gcc
      - git
      - gpg
      - jq
      - llvm
      - lynx
      - make
      - net-tools
      - ripgrep
      - rsync
      - stow
      - tmux
      - tree
      - unzip
      - vim
      - wget
      - zlib1g-dev
      - zsh

  pre_tasks:
  - name: Update apt cache
    apt:
      update_cache: true
      upgrade: "dist"
  - name: Update dist
    apt:
      update_cache: true

  tasks:
  - name: Install packages
    apt:
      name: "{{ item }}"
      state: latest
    loop: "{{ packages }}"
  - name: Install pnpm
    command: curl -fsSL https://get.pnpm.io/install.sh | PNPM_VERSION=7.0.0-rc.3 sh -
