---
- name: Install tools
  hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    packages:
      - bash
      - build-essential
      - curl
      - dash
      - fd-find
      - fzf
      - git
      - gpg
      - jq
      - llvm
      - lynx
      - make
      - net-tools
      - ripgrep
      - stow
      - tmux
      - tree
      - unzip
      - vim
      - wget
      - zsh

  pre_tasks:
  - name: Update apt cache
    apt:
      update_cache: true

  tasks:
  - name: Install packages
    apt:
      name: "{{ item }}"
      state: latest
    loop: "{{ packages }}"
